---
title: "2 module"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MDD vs Control

## 0 setup

```{r}
library(WGCNA)
options(stringsAsFactors = FALSE)
enableWGCNAThreads()
lnames = load(file = "/Users/lucyhui/Downloads/SUDS/Consensus/1 Data input/Consensus-dataInput.RData")
lnames
nSets = checkSets(multiExpr)$nSets
```

## 2a soft thresholding power

```{r}
# choose a set of soft thesholding powers
powers = c(seq(4,10, by=1), seq(12,20,by=2))

# initialize a list to hold the results of scale free analysis
powerTables = vector(mode = "list", length = nSets)

# call the network topology analysis function for each set in turn
for (set in 1:nSets)
  powerTables[[set]] = list(data = pickSoftThreshold(multiExpr[[set]]$data, powerVector = powers, verbose =2)[[2]])
collectGarbage()

# plot result
colors = c("black", "red")
plotCols = c(2,5,6,7) # plot these columns of returned scale free analysis tables
colNames = c("Scale Free Topolgoy Model Fit", "Mean connectivity", "Median connectivity", "Max connectivity")
ylim = matrix(NA, nrow=2, ncol=4) # get mimnima and maxima of plotted points
for (set in 1:nSets)
{
  for(col in 1:length(plotCols))
  {
    ylim[1,col] = min(ylim[1,col], powerTables[[set]]$data[,plotCols[col]], na.rm = TRUE)
    ylim[2,col] = max(ylim[2, col], powerTables[[set]]$data[,plotCols[col]], na.rm = TRUE)
  }
}

sizeGrWindow(8,6)
par(mfcol=c(2,2))
par(mar = c(4.2, 4.2, 2.2, 0.5))
cex1 = 0.7
for (col in 1:length(plotCols)) for (set in 1:nSets)
{
  if (set == 1)
  {
    plot(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2], 
         xlab="Soft Theshold (power)", ylab=colNames[col], type="n", ylim=ylim[,col],
         main = colNames[col])
    addGrid()
  }
  if (col ==1)
  {
    text(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2],
         labels=powers, cex=cex1, col=colors[set])
  } else
    text(powerTables[[set]]$data[,1], powerTables[[set]]$data[,plotCols[col]],
         labels = powers, cex = cex1, col = colors[set])
  if (col == 1)
  {
    legend("bottomright", legend = setLabels, col = colors, pch = 20)
  } else
    legend("topright", legend = setLabels, col = colors, pch = 20)
}
```

## 2b network construction

```{r}
net = blockwiseConsensusModules(
  multiExpr, power = 6, minModuleSize = 1, deepSplit = 2,
  pamRespectsDendro = FALSE,
  mergeCutHeight = 0.25, numericLabels = TRUE,
  minKMEtoStay = 0,
  saveTOMs = TRUE, verbose.= 5
)

# save meaningful variables
consMEs = net$multiMEs
moduleLabels = net$colors
moduleColors = labels2colors(moduleLabels) # convert numeric labels to color labels
consTree = net$dendrograms[[1]]

# dendrogram
sizeGrWindow(8,6)
plotDendroAndColors(consTree, moduleColors,
                    "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05,
                    main = "Consensus marker dendrogram and module colors")
```

## Module output
```{r}
MDDControlmodules = data.frame(markers = names(moduleLabels),
                        module = moduleColors)

write.csv(MDDControlmodules, file = "MDD-Control.csv")
```

## 2c save

```{r}
save(consMEs, moduleLabels, moduleColors, consTree, file = "Consensus-networkConstruction-auto.RData")
```



# MDD M vs F

## 0 setup

```{r}
library(WGCNA)
options(stringsAsFactors = FALSE)
enableWGCNAThreads()
lnames = load(file = "/Users/lucyhui/Downloads/SUDS/Consensus/1 Data input/Consensus-MDDMFdataInput.RData")
lnames
nSets = checkSets(multiExpr)$nSets
```

## 2a soft thresholding power

```{r}
# choose a set of soft thesholding powers
powers = c(seq(4,10, by=1), seq(12,20,by=2))

# initialize a list to hold the results of scale free analysis
powerTables = vector(mode = "list", length = nSets)

# call the network topology analysis function for each set in turn
for (set in 1:nSets)
  powerTables[[set]] = list(data = pickSoftThreshold(multiExpr[[set]]$data, powerVector = powers, verbose =2)[[2]])
collectGarbage()

# plot result
colors = c("black", "red")
plotCols = c(2,5,6,7) # plot these columns of returned scale free analysis tables
colNames = c("Scale Free Topolgoy Model Fit", "Mean connectivity", "Median connectivity", "Max connectivity")
ylim = matrix(NA, nrow=2, ncol=4) # get mimnima and maxima of plotted points
for (set in 1:nSets)
{
  for(col in 1:length(plotCols))
  {
    ylim[1,col] = min(ylim[1,col], powerTables[[set]]$data[,plotCols[col]], na.rm = TRUE)
    ylim[2,col] = max(ylim[2, col], powerTables[[set]]$data[,plotCols[col]], na.rm = TRUE)
  }
}

sizeGrWindow(8,6)
par(mfcol=c(2,2))
par(mar = c(4.2, 4.2, 2.2, 0.5))
cex1 = 0.7
for (col in 1:length(plotCols)) for (set in 1:nSets)
{
  if (set == 1)
  {
    plot(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2], 
         xlab="Soft Theshold (power)", ylab=colNames[col], type="n", ylim=ylim[,col],
         main = colNames[col])
    addGrid()
  }
  if (col ==1)
  {
    text(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2],
         labels=powers, cex=cex1, col=colors[set])
  } else
    text(powerTables[[set]]$data[,1], powerTables[[set]]$data[,plotCols[col]],
         labels = powers, cex = cex1, col = colors[set])
  if (col == 1)
  {
    legend("bottomright", legend = setLabels, col = colors, pch = 20)
  } else
    legend("topright", legend = setLabels, col = colors, pch = 20)
}
```

## 2b network construction

```{r}
net = blockwiseConsensusModules(
  multiExpr, power = 6, minModuleSize = 1, deepSplit = 2,
  pamRespectsDendro = FALSE,
  mergeCutHeight = 0.25, numericLabels = TRUE,
  minKMEtoStay = 0,
  saveTOMs = TRUE, verbose.= 5
)

# save meaningful variables
consMEs = net$multiMEs
moduleLabels = net$colors
moduleColors = labels2colors(moduleLabels) # convert numeric labels to color labels
consTree = net$dendrograms[[1]]

# dendrogram
sizeGrWindow(8,6)
plotDendroAndColors(consTree, moduleColors,
                    "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05,
                    main = "Consensus marker dendrogram and module colors")
```

## Module output
```{r}
MDDMFmodules = data.frame(markers = names(moduleLabels),
                        module = moduleColors)

write.csv(MDDMFmodules, file = "MDD-MF.csv")
```

## 2c save

```{r}
save(consMEs, moduleLabels, moduleColors, consTree, file = "Consensus-MDDMF-networkConstruction-auto.RData")
```

# Control M vs F 

## 0 setup

```{r}
library(WGCNA)
options(stringsAsFactors = FALSE)
enableWGCNAThreads()
lnames = load(file = "/Users/lucyhui/Downloads/SUDS/Consensus/1 Data input/Consensus-ControlMFdataInput.RData")
lnames
nSets = checkSets(multiExpr)$nSets
```

## 2a soft thresholding power

```{r}
# choose a set of soft thesholding powers
powers = c(seq(4,10, by=1), seq(12,20,by=2))

# initialize a list to hold the results of scale free analysis
powerTables = vector(mode = "list", length = nSets)

# call the network topology analysis function for each set in turn
for (set in 1:nSets)
  powerTables[[set]] = list(data = pickSoftThreshold(multiExpr[[set]]$data, powerVector = powers, verbose =2)[[2]])
collectGarbage()

# plot result
colors = c("black", "red")
plotCols = c(2,5,6,7) # plot these columns of returned scale free analysis tables
colNames = c("Scale Free Topolgoy Model Fit", "Mean connectivity", "Median connectivity", "Max connectivity")
ylim = matrix(NA, nrow=2, ncol=4) # get mimnima and maxima of plotted points
for (set in 1:nSets)
{
  for(col in 1:length(plotCols))
  {
    ylim[1,col] = min(ylim[1,col], powerTables[[set]]$data[,plotCols[col]], na.rm = TRUE)
    ylim[2,col] = max(ylim[2, col], powerTables[[set]]$data[,plotCols[col]], na.rm = TRUE)
  }
}

sizeGrWindow(8,6)
par(mfcol=c(2,2))
par(mar = c(4.2, 4.2, 2.2, 0.5))
cex1 = 0.7
for (col in 1:length(plotCols)) for (set in 1:nSets)
{
  if (set == 1)
  {
    plot(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2], 
         xlab="Soft Theshold (power)", ylab=colNames[col], type="n", ylim=ylim[,col],
         main = colNames[col])
    addGrid()
  }
  if (col ==1)
  {
    text(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2],
         labels=powers, cex=cex1, col=colors[set])
  } else
    text(powerTables[[set]]$data[,1], powerTables[[set]]$data[,plotCols[col]],
         labels = powers, cex = cex1, col = colors[set])
  if (col == 1)
  {
    legend("bottomright", legend = setLabels, col = colors, pch = 20)
  } else
    legend("topright", legend = setLabels, col = colors, pch = 20)
}
```

## 2b network construction


```{r}
net = blockwiseConsensusModules(
  multiExpr, power = 8, minModuleSize = 1, deepSplit = 2,
  pamRespectsDendro = FALSE,
  mergeCutHeight = 0.25, numericLabels = TRUE,
  minKMEtoStay = 0,
  saveTOMs = TRUE, verbose.= 5
)

# align color with module length 
order <- net$colors
colors <- net[["dendrograms"]][[1]][["order"]]

if (length(colors) != length(order)) {
  order <- rep(order, length.out = length(colors))
}

net$colors <- order

# save meaningful variables
consMEs = net$multiMEs
moduleLabels = net$colors
moduleColors = labels2colors(moduleLabels) # convert numeric labels to color labels
consTree = net$dendrograms[[1]]

# dendrogram
sizeGrWindow(8,6)
plotDendroAndColors(consTree, moduleColors,
                    "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05,
                    main = "Consensus marker dendrogram and module colors")
```

## Module output
```{r}
ControlMFmodules = data.frame(markers = names(moduleLabels),
                        module = moduleColors)

write.csv(ControlMFmodules, file = "Control-MF.csv")
```

## 2c save

```{r}
save(consMEs, moduleLabels, moduleColors, consTree, file = "Consensus-ControlMF-networkConstruction-auto.RData")
```