---
title: "1 data input"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 0 setup
```{r}
library(WGCNA);
options(stringsAsFactors = FALSE)
MDDinfData = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Inflammatory markers/CBN01_CYTORAWL_DATA_Z3_01_V01_TRTMT.csv")
CntrlinfData = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Inflammatory markers/CBN01_CYTORAWL_DATA_Z3_01_V01_CNTRL.csv")
```

## 1a data input

```{r}
# For easier labeling of plots, create a vector holding descriptive names of the two sets.
nSets = 2;
setLabels = c("MDD markers", "Control markers")
shortLabels = c("MDD", "Control")

# Form multi-set expression data: columns starting from 9 contain actual expression data.
multiExpr = vector(mode = "list", length = nSets)

multiExpr[[1]] = list(data = as.data.frame(MDDinfData[,-c(1:4,34)]))
rownames(multiExpr[[1]]$data) = MDDinfData$SUBJLABEL

multiExpr[[2]] = list(data = as.data.frame(CntrlinfData[,-c(1:4,34)]))
rownames(multiExpr[[2]]$data) = CntrlinfData$SUBJLABEL

# Check that the data has the correct format for many functions operating on multiple sets:
exprSize = checkSets(multiExpr)
```

## 1b data cleaning and outlier removal

Remove missing data 

```{r}
# check all genes and samples have sufficiently low numbers of missing values
gsg = goodSamplesGenesMS(multiExpr, verbose=3)

# if return FALSE use the following code to remove offending samples and genes
if (!gsg$allOK)
{
  # print information about removed genes
  if (sum(!gsg$goodGenes)>0)
    printFlush(paste("Removing genes:", paste(names(multiExpr[[1]]$data[!gsg$goodGenes]), collapse = ",")))
  for (set in 1:exprSize$nSets)
  {
    if (sum(!gsg$goodSamples[[set]]))
      printFlush(paste("In set", setLabels[set], "removing samples", paste(rownames(multiExpr[[set]]$data)[!gsg$goodSamples[[set]]], collapse = ",")))
    # remove the offending genes and samples
    multiExpr[[set]]$data = multiExpr[[set]]$data[gsg$goodSamples[[set]], gsg$goodGenes]
  }
  # update exprSize
  exprSize = checkSets(multiExpr)
}

```
Identify outlier 

```{r}
# cluster samples on their Euclidean distance, separately in each set
sampleTrees = list()
for (set in 1:nSets)
{
  sampleTrees[[set]] = hclust(dist(multiExpr[[set]]$data), method = "average")
}

# dendrograms
pdf(file = "SampleClustering.pdf", width = 12, height = 12)
par(mfrow=c(2,1))
par(mar=c(0,4,2,0))
for(set in 1:nSets)
  plot(sampleTrees[[set]], main = paste("Sample clustering on all markers in", setLabels[set]), xlab="", sub="", cex=0.7)
dev.off()
```

Remove outlier 

```{r}
# choose height cut
cutHeights = c(5000,7000) 

# visualize
pdf(file = "SampleClustering.pdf", width = 12, height = 12)
par(mfrow=c(2,1))
par(mar=c(0,4,2,0))
for(set in 1:nSets)
{
  plot(sampleTrees[[set]], main = paste("Sample clustering on all genes in", setLabels[set]), xlab="", sub="", cex=0.7)
  abline(h=cutHeights[set], col="red")
}
dev.off()

# remove - remove outlier by choice of height cut
for (set in 1:nSets)
{
  # find clusters cut by the line
  labels = cutreeStatic(sampleTrees[[set]], cutHeight = cutHeights[set])
  # keep the largest one (labeled by the number 1)
  keep = (labels == 1)
  multiExpr[[set]]$data = multiExpr[[set]]$data[keep,]
}
collectGarbage()
```

Check size of leftover data

```{r}
# check sie of leftover data
exprSize = checkSets(multiExpr)
exprSize
```

## 1c load clinical trait - depression

```{r}
## MDD 
# import dataframes
MDDcgi = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_CGI_DATA_Z3_01_V01_TRTMT.csv")
MDDgad = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_GAD7_DATA_Z3_01_V01_TRTMT.csv")
MDDmadrs = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_MADRS_DATA_Z3_01_V01_TRTMT.csv")
MDDqids = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_QIDS_DATA_Z3_01_V01_TRTMT.csv")

# merge dataframes
MDDdep <- merge(MDDcgi, MDDgad, by = "SUBJLABEL", all = TRUE)
MDDdep0 <- merge(MDDmadrs, MDDqids, by = "SUBJLABEL", all = TRUE)
MDDdep <- merge(MDDdep, MDDdep0, by = "SUBJLABEL", all = TRUE)

# select columns
MDDdep = MDDdep[,c("SUBJLABEL", "GAD7_Tot", "MADRS_TOT_PRO_RATED", "QIDS_OVERL_SEVTY")]

## Control
# import dataframes
Cntrlcgi = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_CGI_DATA_Z3_01_V01_CNTRL.csv")
Cntrlgad = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_GAD7_DATA_Z3_01_V01_CNTRL.csv")
Cntrlmadrs = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_MADRS_DATA_Z3_01_V01_CNTRL.csv")
Cntrlqids = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_QIDS_DATA_Z3_01_V01_CNTRL.csv")

# merge dataframes
Cntrldep <- merge(Cntrlcgi, Cntrlgad, by = "SUBJLABEL", all = TRUE)
Cntrldep0 <- merge(Cntrlmadrs, Cntrlqids, by = "SUBJLABEL", all = TRUE)
Cntrldep <- merge(Cntrldep, Cntrldep0, by = "SUBJLABEL", all = TRUE)

# select columns
Cntrldep = Cntrldep[,c("SUBJLABEL", "GAD7_Tot", "MADRS_TOT_PRO_RATED", "QIDS_OVERL_SEVTY")]
```

Multi-set structure

```{r}
# from a multi-set structure that will hold the clinical traits
Traits = vector(mode="list", length = nSets);

setSamples = rownames(multiExpr[[1]]$data);
traitRows = match(setSamples, MDDdep$SUBJLABEL);
Traits[[1]] = list(data = MDDdep[traitRows, -1]);
rownames(Traits[[1]]$data) = MDDdep[traitRows, 1];

setSamples = rownames(multiExpr[[2]]$data);
traitRows = match(setSamples, Cntrldep$SUBJLABEL);
Traits[[2]] = list(data = Cntrldep[traitRows, -1]);
rownames(Traits[[2]]$data) = Cntrldep[traitRows, 1];

collectGarbage();

# define data set dimensions 
nGenes = exprSize$nGenes
nSamples = exprSize$nSamples
```

Save

```{r}
# save relevant data for use in subsequent analysis
save(multiExpr, Traits, nGenes, nSamples, setLabels, shortLabels, exprSize, file = "Consensus-dataInput.RData")
```

