---
title: "4 Relating consensus module to Traits"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 0 setup

```{r}
library(WGCNA)
options(stringsAsFactors = FALSE)
lnames = load(file = "/Users/lucyhui/Downloads/SUDS/Consensus/1 Data input/Consensus-dataInput.RData")
lnames
lnames = load(file = "/Users/lucyhui/Downloads/SUDS/Consensus/2 Module/Consensus-networkConstruction-auto.RData")
lnames
exprSize = checkSets(multiExpr)
nSets = exprSize$nSets
```

## 4a relating modules to external traits

```{r}
# set up variables to contain module trait correlations
moduleTraitCor = list()
moduleTraitPvalue = list()

# calculate correlations
for (set in 1:nSets)
{
  moduleTraitCor[[set]] = cor(consMEs[[set]]$data, Traits[[set]]$data, use = "p")
  moduleTraitPvalue[[set]] = corPvalueFisher(moduleTraitCor[[set]], exprSize$nSamples[set])
}
```

We print the correlations and the corresponding p-values, and color-code the entris by the p-value significance

```{r}
# convert numerical labels to colors for labeling of modules in the plot
MEColors = labels2colors(as.numeric(substring(names(consMEs[[1]]$data),3)))
MEColorNames = paste("ME", MEColors, sep="")

sizeGrWindow(10,7)

# MDD
set = 1
textMatrix = paste(signif(moduleTraitCor[[set]],2), "\n(",
                   signif(moduleTraitPvalue[[set]],1), ")", sep="")
dim(textMatrix) = dim(moduleTraitCor[[set]])
par(mar = c(6,8.8,3,2.2))
labeledHeatmap(Matrix = moduleTraitCor[[set]],
               xLabels = names(Traits[[set]]$data),
               yLabels = MEColorNames,
               ySymbols = MEColorNames,
               colorLabels = FALSE,
               colors = greenWhiteRed(50),
               textMatrix = textMatrix,
               setStdMargins = FALSE,
               cex.text = 0.5,
               zlim = c(-1,1),
               main = paste("Module--trait relationships in", setLabels[set]))


# Control
set = 2
textMatrix = paste(signif(moduleTraitCor[[set]],2), "\n(",
                   signif(moduleTraitPvalue[[set]],1), ")", sep="")
dim(textMatrix) = dim(moduleTraitCor[[set]])
par(mar = c(6,8.8,3,2.2))
labeledHeatmap(Matrix = moduleTraitCor[[set]],
               xLabels = names(Traits[[set]]$data),
               yLabels = MEColorNames,
               ySymbols = MEColorNames,
               colorLabels = FALSE,
               colors = greenWhiteRed(50),
               textMatrix = textMatrix,
               setStdMargins = FALSE,
               cex.text = 0.5,
               zlim = c(-1,1),
               main = paste("Module--trait relationships in", setLabels[set]))
```

summarizes the two sets into one measure

```{r}
# initialize matrices to hold the consensus correlation and p value
consensusCor = matrix(NA, nrow(moduleTraitCor[[1]]), ncol(moduleTraitCor[[1]]))
consensusPvalue = matrix(NA, nrow(moduleTraitCor[[1]]), ncol(moduleTraitCor[[1]]))

# find consensus negative correlations
negative = moduleTraitCor[[1]] < 0 & moduleTraitCor[[2]] < 0
consensusCor[negative] = pmax(moduleTraitCor[[1]][negative],moduleTraitCor[[2]][negative])
consensusPvalue[negative] = pmax(moduleTraitPvalue[[1]][negative],moduleTraitPvalue[[2]][negative])

# find consensus positive correlations
positive = moduleTraitCor[[1]] > 0 & moduleTraitCor[[2]] < 0
consensusCor[positive] = pmax(moduleTraitCor[[1]][positive],moduleTraitCor[[2]][positive])
consensusPvalue[positive] = pmax(moduleTraitPvalue[[1]][positive],moduleTraitPvalue[[2]][positive])

# display consensus module-trait relationships
textMatrix = paste(signif(consensusCor, 2), "\n(",
                   signif(consensusPvalue, 1), ")", sep="")
dim(textMatrix) = dim(moduleTraitCor[[set]])
sizeGrWindow(10,7)
par(mar=c(6,8.8,3,2.2))
labeledHeatmap(Matrix=consensusCor,
               xLabels = names(Traits[[set]]$data),
               yLabels = MEColorNames,
               ySymbols = MEColorNames,
               colorLabels = FALSE,
               colors = greenWhiteRed(50),
               textMatrix = textMatrix,
               setStdMargins = FALSE,
               cex.text=0.5,
               zlim=c(-1,1),
               main=paste("Consensus module--trait relationships across\n", paste(setLabels, collapse=" and ")))
```

## 4b export results

```{r}
probes = names(multiExpr[[1]]$data)

# recalculate module eigengenes in alphabetic order and calculate gene significance and module memberships in each data set
consMEs.unord = multiSetMEs(multiExpr, universalColors = moduleLabels, excludeGrey = TRUE)
GS = list()
kME = list()
for (set in 1:nSets)
{
  GS[[set]] = corAndPvalue(multiExpr[[set]]$data, Traits[[set]]$data)
  kME[[set]] = corAndPvalue(multiExpr[[set]]$data, consMEs.unord[[set]]$data)
}

# perform meta analysis by combining Z scores of correlations from each set to form a meta Z score and corresponding P value
GS.metaZ = (GS[[1]]$Z + GS[[2]]$Z)/sqrt(2)
kME.metaZ = (kME[[1]]$Z + kME[[2]]$Z)/sqrt(2)
GS.metaP = 2*pnorm(abs(GS.metaZ), lower.tail = FALSE)
kME.metaP = 2*pnorm(abs(kME.metaZ), lower.tail = FALSE)

# form matrices holding GS (gene significances) and kME (module memberships)
# use simple reshaping trick to put values and associated p values and met analysis results next to one another
GSmat = rbind(GS[[1]]$cor, GS[[2]]$cor, GS[[1]]$p, GS[[2]]$p, GS.metaZ, GS.metaP)
nTraits = checkSets(Traits)$nGenes
traitNames = colnames(Traits[[1]]$data)
dim(GSmat) = c(nGenes, 6*nTraits)
rownames(GSmat) = probes
colnames(GSmat) = spaste(
  c("GS.set1.", "GS.set2.", "p.GS.set1.", "p.GS.set2.", "Z.GS.meta.", "p.GS.meta."),
  rep(traitNames, rep(6,nTraits)))
# same code for kME
kMEmat = rbind(kME[[1]]$cor, kME[[2]]$cor, kME[[1]]$p, kME[[2]]$p, kME.metaZ, kME.metaP)
MEnames = colnames(consMEs.unord[[1]]$data)
nMEs = checkSets(consMEs.unord)$nGenes
dim(kMEmat) = c(nGenes, 6*nMEs)
rownames(kMEmat) = probes
colnames(kMEmat) = spaste(
  c("kME.set1.", "kME.set2.", "p.kME.set1.", "p.kME.set2.", "Z.kME.meta.", "p.kME.meta."),
  rep(MEnames, rep(6,nMEs)))

# put together full information in data frame to CSV 
info = data.frame(Probe = probes, ModuleLabel = moduleLabels,
                  ModuleColor = labels2colors(moduleLabels),
                  GSmat,
                  kMEmat)
write.csv(info, file = "consensusAnalysis-CombinedNetworkResults.csv", row.names=FALSE, quote=FALSE)
```

