---
title: "Depression"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MDD

## clean dataframes

```{r}
library(dplyr)
library(WGCNA)
options(stringsAsFactors = FALSE)

# import dataframes
MDDcgi = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_CGI_DATA_Z3_01_V01_TRTMT.csv")
MDDgad = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_GAD7_DATA_Z3_01_V01_TRTMT.csv")
MDDmadrs = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_MADRS_DATA_Z3_01_V01_TRTMT.csv")
MDDqids = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_QIDS_DATA_Z3_01_V01_TRTMT.csv")

# merge dataframes
MDDdep <- merge(MDDcgi, MDDgad, by = "SUBJLABEL", all = TRUE)
MDDdep0 <- merge(MDDmadrs, MDDqids, by = "SUBJLABEL", all = TRUE)
MDDdep <- merge(MDDdep, MDDdep0, by = "SUBJLABEL", all = TRUE)

# select columns
MDDdep = MDDdep[,c("SUBJLABEL", "GAD7_Tot", "MADRS_TOT_PRO_RATED", "QIDS_OVERL_SEVTY")]
```

## restructure dataframe so it's analogous to marker data

```{r}
traitRows = match(rownames(MDDinfData5), MDDdep$SUBJLABEL)
MDDdep2 = MDDdep[traitRows, -1]
rownames(MDDdep2) = MDDdep[traitRows, 1]
```

## We visualize how the clinical traits relate to the sample dendrogram.

```{r}
# white means low value, red means high value, grey means missing entry
sampleTree2 = hclust(dist(MDDinfData5), method = "average")
traitColors = numbers2colors(MDDdep2, signed = FALSE)
plotDendroAndColors(sampleTree2, traitColors, groupLabels = names(MDDdep2), main = "Sample dendrogram and trait heatmap")
```

Save results for the next step.

```{r}
save(MDDinfData5, MDDdep2, file = "MDDinfDep.RData")
```



# Control

## clean dataframes

```{r}
library(dplyr)
library(WGCNA)
options(stringsAsFactors = FALSE)

# import dataframes
Cntrlcgi = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_CGI_DATA_Z3_01_V01_CNTRL.csv")
Cntrlgad = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_GAD7_DATA_Z3_01_V01_CNTRL.csv")
Cntrlmadrs = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_MADRS_DATA_Z3_01_V01_CNTRL.csv")
Cntrlqids = read.csv("/Users/lucyhui/Downloads/SUDS/Individual/1 data input/Depression/CBN01_QIDS_DATA_Z3_01_V01_CNTRL.csv")

# merge dataframes
Cntrldep <- merge(Cntrlcgi, Cntrlgad, by = "SUBJLABEL", all = TRUE)
Cntrldep0 <- merge(Cntrlmadrs, Cntrlqids, by = "SUBJLABEL", all = TRUE)
Cntrldep <- merge(Cntrldep, Cntrldep0, by = "SUBJLABEL", all = TRUE)

# select columns
Cntrldep = Cntrldep[,c("SUBJLABEL", "GAD7_Tot", "MADRS_TOT_PRO_RATED", "QIDS_OVERL_SEVTY")]
```

## restructure dataframe so it's analogous to marker data

```{r}
traitRows = match(rownames(CntrlinfData5), Cntrldep$SUBJLABEL)
Cntrldep2 = Cntrldep[traitRows, -1]
rownames(Cntrldep2) = Cntrldep[traitRows, 1]
```

## We visualize how the clinical traits relate to the sample dendrogram.

```{r}
# white means low value, red means high value, grey means missing entry
sampleTree2 = hclust(dist(CntrlinfData5), method = "average")
traitColors = numbers2colors(Cntrldep2, signed = FALSE)
plotDendroAndColors(sampleTree2, traitColors, groupLabels = names(Cntrldep2), main = "Sample dendrogram and trait heatmap")
```

```{r}
save(CntrlinfData5, Cntrldep2, file = "CntrlInfDep.RData")
```
